-- Events seed (24). Generated by build_sql.py from events.json and event-tags.json.
-- Idempotent on (source, external_id); needs the contract's unique index on that pair.
insert into events (source, external_id, source_url, title_en, title_th, description_en, description_th, starts_at, ends_at, venue_name, address, price_text, image_url) values
  ('seed', 'claude-impact-lab', 'https://luma.com/claude-ru1w', 'Claude Code Impact Lab: a hackathon for Chiang Mai', 'Claude Code Impact Lab แฮกกาธอนเพื่อเมืองเชียงใหม่', 'A two-day hackathon where developers, designers and people who know local problems build tools for the community, with Cosmo Local and Chiang Mai Municipality.
Teams of 4–5 build with Claude for a day, then present to a jury. Every project is open-sourced on GitHub and handed to the partners to take forward.
Conversational English is enough.
• Free, but you need to apply and be accepted
• Non-technical people are genuinely wanted: local knowledge is the most valuable thing in the room
• Follow the Luma page for the next round', 'แฮกกาธอน 2 วันที่นักพัฒนา นักออกแบบ และคนที่เข้าใจปัญหาในพื้นที่ มาสร้างเครื่องมือเพื่อชุมชนร่วมกับ Cosmo Local และเทศบาลนครเชียงใหม่
ทีมละ 4–5 คนใช้ Claude สร้างผลงานภายในวันเดียว แล้วนำเสนอต่อกรรมการ ทุกผลงานเปิดซอร์สบน GitHub และส่งต่อให้ภาคีนำไปใช้ต่อ
ภาษาอังกฤษพอคุยได้ก็พอ
• ฟรี แต่ต้องสมัครและผ่านการคัดเลือกก่อน
• ผู้จัดตั้งใจรับคนที่ไม่ใช่สายเทคด้วย ความเข้าใจปัญหาในพื้นที่คือสิ่งที่มีค่าที่สุดในห้อง
• ติดตามรอบถัดไปได้ที่หน้า Luma ของงาน', '2026-09-26T17:00:00+07:00', '2026-09-27T15:00:00+07:00', 'Shared after you''re accepted', 'Mueang Chiang Mai, Chiang Mai', 'Free (application required)', 'https://images.lumacdn.com/api-uploads/8b/285aa513-cdcf-4ac3-aba7-1a6327e2732b.png'),
  ('seed', 'ai-news-meetup', 'https://www.meetup.com/ai-fusion-labs-chiang-mai/events/316452633/', 'AI News Community Meetup', 'วงคุยข่าว AI ประจำสัปดาห์', 'Talk through this week''s AI news and share free and low-cost tools. Small business owners, creators, freelancers and beginners especially welcome.
Over coffee, go through the week''s AI news and new tools, then swap practical tips.
Conversational English is enough.
• 200 baht, includes one drink
• Beginners welcome, no technical background needed
• It''s downstairs at Story 106', 'คุยข่าว AI ล่าสุด แชร์เครื่องมือฟรีและราคาถูก เหมาะกับเจ้าของกิจการเล็ก ครีเอเตอร์ ฟรีแลนซ์ และมือใหม่
นั่งจิบกาแฟ คุยเรื่องข่าวและเครื่องมือ AI ใหม่ ๆ ของสัปดาห์ แล้วแลกเทคนิคใช้งานจริงกัน
ภาษาอังกฤษพอคุยได้ก็พอ
• ค่าเข้า 200 บาท ได้เครื่องดื่ม 1 แก้ว
• มือใหม่ยินดีต้อนรับ ไม่ต้องมีพื้นฐานเทคนิค
• ร้านอยู่ชั้นล่างของ Story 106', '2026-09-27T11:00:00+07:00', '2026-09-27T12:30:00+07:00', 'The Story 106 Co-Working Space & Cafe', 'The Story 106 Tha Phae Road Chiang Mai', '200 baht incl. drink', 'https://secure-content.meetupstatic.com/images/classic-events/535638172/676x380.jpg'),
  ('seed', 'temple-cleanup', 'https://www.meetup.com/chiang-mai-meditation-buddhist-study-community/events/313631235/', 'Temple Clean-Up Day at Wat Tung Yu', 'จิตอาสาทำความสะอาดวัดทุงยู', 'Help clean a 500-year-old temple in the Old City, alongside the foreign community that studies meditation there.
Give your time or bring cleaning supplies to donate. Everyone works together as one big group; families welcome.
Little English needed.
• Free
• Mostly hands-on work, very little English needed
• Come at 9:00 for meditation and a Dhamma talk in English first
• Dress modestly for the temple, in clothes that can get dirty', 'ช่วยกันทำความสะอาดวัดอายุกว่า 500 ปีกลางเมือง ร่วมกับกลุ่มชาวต่างชาติที่มาเรียนธรรมะที่นี่
มาช่วยแรง หรือนำอุปกรณ์ทำความสะอาดมาร่วมบริจาค ทำด้วยกันเป็นกลุ่มใหญ่ พาครอบครัวมาได้
ใช้ภาษาอังกฤษน้อย
• ฟรี
• ทำงานด้วยมือเป็นหลัก ใช้ภาษาอังกฤษน้อยมาก
• ถ้ามาตั้งแต่ 9 โมง มีนั่งสมาธิและฟังธรรมภาษาอังกฤษก่อน
• แต่งกายสุภาพแบบเข้าวัด และใส่ชุดที่เปื้อนได้', '2026-09-27T11:00:00+07:00', '2026-09-27T12:30:00+07:00', 'Wat Tung Yu', 'Wat Tung Yu Chiang Mai', 'Free', 'https://secure-content.meetupstatic.com/images/classic-events/533030571/676x380.jpg'),
  ('seed', 'sunday-brunch', 'https://www.meetup.com/chiang-mai-professionals-expats-and-digital-nomads/events/316634361/', 'Sunday Brunch by Nomads Chiang Mai', 'บรันช์วันอาทิตย์ของชุมชนโนแมด', 'A relaxed brunch that deliberately puts locals, expats and newcomers at the same table.
No agenda, no presentations. Eat and talk, sometimes light, sometimes deep. A host welcomes everyone.
Conversational English is enough.
• 50 baht to join, and you order your own food and drinks
• The organizer says clearly that locals are welcome
• Fine to come alone; the host will introduce you around', 'บรันช์สบาย ๆ ที่ตั้งใจรวมคนท้องถิ่น ชาวต่างชาติ และคนย้ายมาใหม่ไว้ในโต๊ะเดียวกัน
ไม่มีวาระ ไม่มีการพรีเซนต์ นั่งกิน นั่งคุย บางทีคุยเล่น บางทีคุยลึก มีโฮสต์คอยต้อนรับ
ภาษาอังกฤษพอคุยได้ก็พอ
• ค่าร่วมงาน 50 บาท และต้องสั่งอาหารหรือเครื่องดื่มเอง
• ผู้จัดเขียนไว้ชัดว่าเปิดรับคนท้องถิ่นด้วย
• มาคนเดียวได้ โฮสต์จะช่วยแนะนำให้รู้จักคนอื่น', '2026-09-27T11:30:00+07:00', '2026-09-27T13:30:00+07:00', 'Hideaway', 'Hideaway Cafe Pa Daet Chiang Mai', '50 baht + food', 'https://secure-content.meetupstatic.com/images/classic-events/528498767/676x380.jpg'),
  ('seed', 'ecstatic-dance', 'https://www.meetup.com/chiang-mai-conscious-dance-meetup-group/events/316453212/', 'Ecstatic Dance CNX', 'Ecstatic Dance เต้นอิสระตามเสียงเพลง', 'Free-form dancing with no steps and no talking, to African, Latin and house music from a DJ.
A short opening and closing circle, with about two hours of free dance in between: barefoot, without words.
Little English needed.
• 300 baht
• No alcohol, no phones, no photos
• Dance barefoot; wear clothes you can move in
• Arrive on time, everyone starts together', 'เต้นแบบไม่มีท่า ไม่ต้องพูด ปล่อยตัวไปกับดนตรีแอฟริกัน ละติน และเฮาส์จากดีเจ
เริ่มและจบด้วยการล้อมวงสั้น ๆ ระหว่างนั้นเต้นอิสระราว 2 ชั่วโมง เท้าเปล่า ไม่คุยกัน
ใช้ภาษาอังกฤษน้อย
• ค่าเข้า 300 บาท
• ห้ามแอลกอฮอล์ ห้ามใช้โทรศัพท์และถ่ายรูป
• ถอดรองเท้าเต้น ใส่ชุดที่ขยับตัวสบาย
• มาให้ตรงเวลา เพราะเริ่มพร้อมกันทุกคน', '2026-09-27T12:30:00+07:00', '2026-09-27T14:30:00+07:00', 'Vivid Dance Studios (upstairs)', 'Vivid Dance Studios Chiang Mai', '300 baht', 'https://secure-content.meetupstatic.com/images/classic-events/533489511/676x380.jpg'),
  ('seed', 'be-real', 'https://www.meetup.com/be-fxcking-real-chiang-mai/events/316646729/', 'Be Real: say what you never tell anyone', 'Be Real วงเล่าเรื่องจริงที่ไม่เคยบอกใคร', 'A small circle for people who want to talk about what''s really going on (loneliness, a stuck business, habits they want to break) without judgement.
In a small group, take turns sharing what''s happening in your life while others listen without rushing to fix it. It ends with each person committing to one brave move.
Fluent English needed.
• The event''s name says locals are welcome
• Deep personal sharing, in English
• The price isn''t stated; check the event page first', 'วงเล็กสำหรับคนที่อยากคุยเรื่องจริงในใจ ทั้งความเหงา งานที่ติดขัด หรือนิสัยที่อยากเลิก โดยไม่มีใครตัดสิน
นั่งเป็นกลุ่มเล็ก ผลัดกันเล่าสิ่งที่เกิดขึ้นกับตัวเอง คนอื่นตั้งใจฟังโดยไม่รีบแนะนำ ปิดท้ายด้วยการตั้งใจทำเรื่องกล้า ๆ หนึ่งอย่าง
ต้องคุยภาษาอังกฤษได้คล่อง
• ชื่องานเขียนไว้เลยว่าเปิดรับคนท้องถิ่น
• เป็นการเล่าเรื่องส่วนตัวลึก ๆ เป็นภาษาอังกฤษ
• ประกาศไม่ระบุค่าเข้า เช็กที่หน้างานก่อนไป', '2026-09-27T14:00:00+07:00', '2026-09-27T15:30:00+07:00', 'Spice Garden', 'Spice Garden Moonmuang Soi 5 Chiang Mai', 'Not stated', 'https://secure-content.meetupstatic.com/images/classic-events/536194738/676x380.jpg'),
  ('seed', 'skate-create', 'https://www.meetup.com/chiang-mai-professionals-expats-and-digital-nomads/events/316239702/', 'Skate X Create', 'Skate X Create โรลเลอร์สเก็ตกับวาดรูปในสวน', 'A lazy afternoon in the railway station park: skaters skate, artists draw, or you just sit on the grass.
Double-dutch jump rope, shared art supplies and music in the background. Come and go whenever you like.
Little English needed.
• Bring skates, a sketchbook, a blanket and snacks
• All levels, no skills needed
• Little English needed; it''s about doing things together', 'บ่ายสบาย ๆ ที่สวนสถานีรถไฟ คนเล่นสเก็ตก็เล่น คนวาดรูปก็วาด หรือจะนั่งเล่นบนหญ้าเฉย ๆ ก็ได้
มีกระโดดเชือกแบบดับเบิลดัตช์ อุปกรณ์วาดรูปให้ใช้ร่วมกัน และเปิดเพลงคลอ มาช่วงไหนกลับช่วงไหนก็ได้
ใช้ภาษาอังกฤษน้อย
• เอาสเก็ต สมุดสเก็ตช์ ผ้าปู และขนมมาได้
• ทุกระดับฝีมือ ไม่ต้องเก่งอะไรเลย
• ใช้ภาษาอังกฤษน้อย ทำกิจกรรมด้วยกันเป็นหลัก', '2026-09-27T14:00:00+07:00', '2026-09-27T18:00:00+07:00', 'Chiang Mai Railway Station park (parking area)', 'Chiang Mai Railway Station', 'Not clearly stated', 'https://secure-content.meetupstatic.com/images/classic-events/535800186/676x380.jpg'),
  ('seed', 'sunday-walking-street', 'https://www.chiangmai-trip.com/destinations/sunday-walking-street/', 'Sunday Walking Street', 'ถนนคนเดินวันอาทิตย์ ถนนราชดำเนิน', 'Chiang Mai''s biggest weekly night market: about a kilometre of handicrafts, art and street food along Ratchadamnoen Road, from Tha Phae Gate to Wat Phra Singh.
Wander, eat and browse at your own pace; the temple courtyards along the way are full of food stalls.
Little English needed.
• Free to walk; bring cash for the stalls
• Easiest between 5 and 7 pm, packed after 7
• The road closes to traffic from about 4 pm', 'ตลาดนัดกลางคืนประจำสัปดาห์ที่ใหญ่ที่สุดของเชียงใหม่ ร้านงานฝีมือ งานศิลปะ และของกินยาวราวหนึ่งกิโลเมตรตลอดถนนราชดำเนิน จากประตูท่าแพถึงวัดพระสิงห์
เดินเล่น กิน ช้อปตามสบาย ลานวัดระหว่างทางมีร้านอาหารเพียบ
ใช้ภาษาอังกฤษน้อย
• เดินฟรี เตรียมเงินสดไว้ซื้อของ
• เดินสบายช่วง 17:00–19:00 น. หลังหนึ่งทุ่มคนแน่นมาก
• ปิดถนนตั้งแต่ราวสี่โมงเย็น', '2026-09-27T16:00:00+07:00', '2026-09-27T23:00:00+07:00', 'Ratchadamnoen Road, Tha Phae Gate to Wat Phra Singh', 'Ratchadamnoen Road, Old City, Chiang Mai', 'Free', null),
  ('seed', 'sunset-walk-cmu', 'https://www.meetup.com/beyond-small-talk-chiang-mai/events/316454663/', 'Sunday Sunset Walk & Connect at CMU', 'เดินชมพระอาทิตย์ตกใน มช. แล้วทำความรู้จักกัน', 'A walk around Chiang Mai University at golden hour, talking with people from many countries.
Walk and talk beyond small talk. The organizer wants locals and newcomers to genuinely get to know each other.
Conversational English is enough.
• The organizer says clearly that locals are welcome
• Wear comfortable walking shoes
• Check the meeting point on the event page before you go', 'เดินเล่นรอบมหาวิทยาลัยเชียงใหม่ช่วงแดดสีทอง พร้อมคุยกับคนจากหลายประเทศ
เดินไปคุยไปแบบลึกกว่าการทักทายทั่วไป ผู้จัดตั้งใจให้คนท้องถิ่นกับคนย้ายมาใหม่ได้รู้จักกันจริง ๆ
ภาษาอังกฤษพอคุยได้ก็พอ
• ผู้จัดเขียนไว้ชัดว่าเปิดรับคนท้องถิ่นด้วย
• ใส่รองเท้าที่เดินสบาย
• ดูจุดนัดพบในหน้างานก่อนไป', '2026-09-27T17:00:00+07:00', '2026-09-27T19:00:00+07:00', 'Chiang Mai University (meeting point on the event page)', 'Chiang Mai University', 'Not stated', 'https://secure-content.meetupstatic.com/images/classic-events/534830098/676x380.jpg'),
  ('seed', 'eco-printing-bua-bhat', 'https://www.airbnb.com.sg/experiences/6258108', 'Eco printing with artisan Wilai at Bua Bhat Factory', 'เวิร์กช็อปพิมพ์ผ้าด้วยใบไม้กับคุณวิไล ที่บัวผัดแฟคทอรี่', 'A hands-on workshop printing scarves with tropical leaves from the garden, led by Wilai, a second-generation textile artisan.
Pick your mordant, match leaves to colours, then sip Thai herbal tea while the prints set. About three hours.
Little English needed: Wilai teaches in Thai and English.
• From 50 SGD per person on Airbnb, speciality drinks included
• Sessions 28–30 Sep, 9 am–12 pm or 1–4 pm; book on Airbnb
• In Buak Khang, outside the city: easiest by Grab', 'เวิร์กช็อปลงมือพิมพ์ผ้าพันคอด้วยใบไม้เมืองร้อนจากสวน สอนโดยคุณวิไล ช่างผ้ารุ่นที่สอง
เลือกสารช่วยติดสี จับคู่ใบไม้กับสี แล้วจิบชาสมุนไพรระหว่างรอให้ลายติด ใช้เวลาประมาณสามชั่วโมง
ใช้ภาษาอังกฤษน้อย คุณวิไลสอนได้ทั้งไทยและอังกฤษ
• เริ่มต้น 50 ดอลลาร์สิงคโปร์ต่อคนบน Airbnb รวมเครื่องดื่ม
• มีรอบ 28–30 ก.ย. เวลา 9:00–12:00 น. หรือ 13:00–16:00 น. จองผ่าน Airbnb
• อยู่ที่บวกค้าง นอกเมือง เดินทางด้วย Grab สะดวกที่สุด', '2026-09-28T09:00:00+07:00', '2026-09-28T12:00:00+07:00', 'Bua Bhat Factory (บัวผัดแฟคทอรี่)', 'Buak Khang, Chiang Mai 50130', 'From 50 SGD', 'https://a0.muscache.com/im/pictures/Mt/MtTemplate-6258108/original/a8445728-e3bc-4536-8d4b-62eb039b65ec.jpeg?im_w=1200'),
  ('seed', 'hiit-tue', 'https://www.meetup.com/hiit-cnx/events/316479586/', 'HIIT Circuit Training & Social Chat', 'เวิร์กเอาต์ HIIT แล้วนั่งคุยกันต่อ', 'A high-intensity circuit workout for all levels, then a relaxed chat to cool down.
Circuit training with easier versions for beginners, followed by a chat to swap fitness tips.
Little English needed.
• Price not stated
• Bring workout clothes, water and a towel
• Little talking during the workout; just follow the moves
• Every Tuesday and Friday', 'ออกกำลังกายแบบเซอร์กิตเข้มข้น ทุกระดับทำได้ แล้วคูลดาวน์ด้วยการนั่งคุยสบาย ๆ
เทรนแบบวงจร มีท่าดัดแปลงให้คนเพิ่งเริ่ม จากนั้นนั่งคุยแลกทิปส์ออกกำลังกายกัน
ใช้ภาษาอังกฤษน้อย
• ประกาศไม่ระบุค่าใช้จ่าย
• เตรียมชุดออกกำลังกาย น้ำ และผ้าขนหนู
• ช่วงออกกำลังแทบไม่ต้องพูด ดูท่าแล้วทำตามได้
• มีทุกวันอังคารและวันศุกร์', '2026-09-29T11:00:00+07:00', '2026-09-29T13:00:00+07:00', 'Decathlon, Central Festival', 'Decathlon Central Festival Chiang Mai', 'Not stated', 'https://secure-content.meetupstatic.com/images/classic-events/534060221/676x380.jpg'),
  ('seed', 'longevity', 'https://www.meetup.com/longevity-circle-chiang-mai/events/316674696/', 'Longevity & Biohacking Meetup', 'วงกาแฟคุยเรื่องอายุยืนและไบโอแฮ็ก', 'Coffee and conversation about eating, sleeping and staying healthy for longer. This week: food and nutrition.
Each week goes deep on one topic, focused on turning what you learn into everyday habits.
Conversational English is enough.
• 200 baht, includes one drink
• Nimman branch, Soi 11
• Some health and science vocabulary', 'คุยเรื่องการกิน การนอน และการดูแลร่างกายให้แข็งแรงไปนาน ๆ สัปดาห์นี้หัวข้ออาหารและโภชนาการ
แต่ละสัปดาห์เจาะลึกหนึ่งหัวข้อ เน้นเปลี่ยนความรู้ให้เป็นสิ่งที่ทำได้จริงในชีวิตประจำวัน
ภาษาอังกฤษพอคุยได้ก็พอ
• ค่าเข้า 200 บาท ได้เครื่องดื่ม 1 แก้ว
• ร้านสาขานิมมาน ซอย 11
• มีศัพท์สุขภาพและวิทยาศาสตร์บ้าง', '2026-09-29T11:00:00+07:00', '2026-09-29T12:30:00+07:00', 'Ombra Caffe Nimman', 'Ombra Caffe Nimman Chiang Mai', '200 baht incl. drink', 'https://secure-content.meetupstatic.com/images/classic-events/531788999/676x380.jpg'),
  ('seed', 'art-craft-circle', 'https://www.meetup.com/lanna-art-craft-culture-lovers/events/316676107/', 'Art & Craft Circle', 'วงงานศิลปะและงานฝีมือ', 'Sketch, paint, make collages or sew together. There''s a weekly theme, but you can work on your own thing.
Make things side by side, trade techniques, encourage each other and talk about works in progress.
Little English needed.
• Suggested donation 100 baht
• Coloured pencils, pens and paper provided, or bring your own
• You connect through the work; not much talking needed', 'มานั่งวาดรูป ระบายสี ทำคอลลาจ หรือเย็บปักด้วยกัน มีธีมให้ทุกสัปดาห์แต่จะทำงานของตัวเองก็ได้
ทำงานไปด้วยกัน แลกเทคนิค ให้กำลังใจกัน และเล่าเรื่องงานที่กำลังทำอยู่
ใช้ภาษาอังกฤษน้อย
• บริจาคตามแนะนำ 100 บาท
• มีสีไม้ ปากกา และกระดาษให้ใช้ หรือเอาอุปกรณ์ตัวเองมาก็ได้
• คุยผ่านงานได้ ไม่ต้องพูดเยอะ', '2026-09-29T15:00:00+07:00', '2026-09-29T16:00:00+07:00', 'Ombra Caffe Nimman', 'Ombra Caffe Nimman Chiang Mai', '100 baht donation', 'https://secure-content.meetupstatic.com/images/classic-events/536047556/676x380.jpg'),
  ('seed', 'sketch-club', 'https://www.meetup.com/attika-studio-chiangmai/events/316420377/', 'Sketch Club at Attika Studio', 'สเก็ตช์คลับที่ Attika Studio', 'Coffee in hand, jazz in the air, drawing every Wednesday afternoon.
Draw together in the café. No booking needed; just show up and start.
Little English needed.
• Free with a drink
• Paper and colour pens provided
• Barely any English needed', 'กาแฟในมือ แจ๊สคลอ วาดรูปไปเรื่อย ๆ ทุกบ่ายวันพุธ
นั่งวาดด้วยกันในคาเฟ่ ไม่ต้องจองล่วงหน้า มาถึงก็เริ่มได้เลย
ใช้ภาษาอังกฤษน้อย
• ฟรีเมื่อสั่งเครื่องดื่ม
• มีกระดาษและปากกาสีให้
• แทบไม่ต้องใช้ภาษาอังกฤษ', '2026-09-30T15:00:00+07:00', '2026-09-30T17:00:00+07:00', 'attika studio Café & Workshop', 'attika studio 63 Tha Phae Road Chiang Mai', 'Free with a drink', 'https://secure-content.meetupstatic.com/images/classic-events/535627755/676x380.jpg'),
  ('seed', 'questions-family', 'https://www.meetup.com/questionsthatmatter/events/316638674/', 'Did We Kill the Family? Wednesday discussion', 'วงสนทนา: เราทำให้ "ครอบครัว" ตายไปแล้วหรือเปล่า', 'A debate on family in an age when people choose not to marry, not to have children, or to cut ties, and what we still owe the people who raised us.
An open circle: share your view or just listen.
Fluent English needed.
• Free
• Fluent English helps to join the debate fully
• Perspectives from Thai and other Asian family cultures are rarely heard in this circle and very welcome', 'ถกกันเรื่องครอบครัวในยุคที่คนเลือกไม่แต่งงาน ไม่มีลูก หรือตัดขาดจากครอบครัว แล้วเรายังติดค้างอะไรกับคนที่เลี้ยงเรามา
นั่งล้อมวงแลกความเห็นกันอย่างเปิดกว้าง ใครอยากพูดก็พูด ใครอยากฟังก็ฟัง
ต้องคุยภาษาอังกฤษได้คล่อง
• ฟรี
• ต้องคุยภาษาอังกฤษคล่องจึงจะร่วมถกได้เต็มที่
• มุมมองเรื่องครอบครัวแบบไทยจะเป็นเสียงที่วงนี้ไม่ค่อยได้ยิน', '2026-09-30T18:00:00+07:00', '2026-09-30T20:00:00+07:00', '4Seas Nimman', '4Seas Nimman Soi 15 Chiang Mai', 'Free', 'https://secure-content.meetupstatic.com/images/classic-events/536232500/676x380.jpg'),
  ('seed', 'ai-business', 'https://www.meetup.com/coding-in-bangkok/events/316497365/', 'AI for Business Weekly', 'AI สำหรับธุรกิจ พบกันทุกสัปดาห์', 'Business owners and managers swap real experience of using AI for automation, content and decision-making.
Tools and strategies for using AI to grow sales and work smarter, practical rather than theoretical.
Conversational English is enough.
• No technical background needed
• Price not stated
• Good for business owners who want to start using AI', 'เจ้าของกิจการและผู้จัดการมาแลกประสบการณ์ใช้ AI จริงในงาน ทั้งระบบอัตโนมัติ คอนเทนต์ และการตัดสินใจ
คุยเรื่องเครื่องมือและกลยุทธ์ใช้ AI เพิ่มยอดขายและประสิทธิภาพ เน้นใช้ได้จริงมากกว่าทฤษฎี
ภาษาอังกฤษพอคุยได้ก็พอ
• ไม่ต้องมีพื้นฐานเทคนิค
• ประกาศไม่ระบุค่าใช้จ่าย
• เหมาะกับเจ้าของกิจการที่อยากเริ่มใช้ AI', '2026-09-30T18:00:00+07:00', '2026-09-30T20:00:00+07:00', '4Seas Nimman', '4Seas Nimman Soi 15 Chiang Mai', 'Not stated', 'https://secure-content.meetupstatic.com/images/classic-events/529453736/676x380.jpg'),
  ('seed', 'reading-club', 'https://www.meetup.com/nimman-circle/events/316704740/', 'Bring-a-Book Reading Club', 'ชวนกันมานั่งอ่านหนังสือเงียบ ๆ', 'Bring any book and read together, without distractions.
A quick intro about what you''re reading, an hour of quiet reading, a short share, then chat as you like.
Little English needed.
• Any language is fine: bring a book in your own language
• No talking at all during the reading hour
• Check the venue on the event page before you go', 'พกหนังสือเล่มไหนก็ได้มานั่งอ่านด้วยกัน โดยไม่มีอะไรมารบกวน
แนะนำตัวสั้น ๆ ว่ากำลังอ่านอะไร อ่านเงียบ ๆ หนึ่งชั่วโมง เล่าให้กันฟังนิดหน่อย แล้วคุยต่อตามสบาย
ใช้ภาษาอังกฤษน้อย
• เอาหนังสือภาษาไทยมาอ่านก็ได้
• ช่วงอ่านไม่ต้องพูดเลย
• ดูสถานที่ในหน้างานก่อนไป', '2026-10-01T09:30:00+07:00', '2026-10-01T11:30:00+07:00', 'See the event page', 'Nimman, Chiang Mai', 'Not stated', 'https://secure-content.meetupstatic.com/images/classic-events/536264947/676x380.jpg'),
  ('seed', 'life-happened', 'https://www.meetup.com/beyond-small-talk-chiang-mai/events/316526284/', 'Has Your Life Already Happened?', 'วงคุยปรัชญา: ชีวิตเราเกิดขึ้นไปหมดแล้วหรือยัง', 'A conversation about time: if the future already exists, what is the present?
A philosophy-and-science discussion where everyone takes turns sharing views.
Fluent English needed.
• Fluent English needed
• Price not stated
• For people who enjoy abstract debates', 'ชวนคิดเรื่องเวลา ถ้าอนาคตมีอยู่แล้ว สิ่งที่เราเรียกว่าปัจจุบันคืออะไร
วงสนทนาเชิงปรัชญาและวิทยาศาสตร์ ผลัดกันแสดงความเห็นในกลุ่ม
ต้องคุยภาษาอังกฤษได้คล่อง
• ต้องใช้ภาษาอังกฤษคล่อง
• ประกาศไม่ระบุค่าใช้จ่าย
• เหมาะกับคนชอบถกเรื่องนามธรรม', '2026-10-01T18:00:00+07:00', '2026-10-01T20:00:00+07:00', 'Spice Garden', 'Spice Garden Moonmuang Soi 5 Chiang Mai', 'Not stated', 'https://secure-content.meetupstatic.com/images/classic-events/536100248/676x380.jpg'),
  ('seed', 'new-in-town', 'https://www.meetup.com/makenewfriendsinchiangmai/events/316511971/', 'New in Town: Welcome to Chiang Mai', 'New in Town งานต้อนรับคนมาใหม่ในเชียงใหม่', 'Icebreaker games to start, then swapping tips on places to go and hidden gems in the city.
Introductions, icebreakers, then tips on living in Chiang Mai. Stay as long as you like.
Conversational English is enough.
• Free, casual dress
• "Anyone is welcome", says the organizer; bring friends
• If you live here, your local food tips are exactly what newcomers want', 'เปิดด้วยเกมทำความรู้จัก แล้วคุยกันเรื่องที่เที่ยวและร้านลับในเมือง
แนะนำตัว เล่นไอซ์เบรกเกอร์ แล้วแลกทิปส์ใช้ชีวิตในเชียงใหม่ อยู่ต่อได้ทั้งคืน
ภาษาอังกฤษพอคุยได้ก็พอ
• ฟรี แต่งตัวสบาย ๆ
• ผู้จัดเขียนว่า Anyone is welcome พาเพื่อนมาได้
• ถ้าคุณเป็นคนเชียงใหม่ ทิปส์ร้านอร่อยของคุณคือสิ่งที่ทุกคนในงานอยากได้', '2026-10-01T18:00:00+07:00', '2026-10-01T21:00:00+07:00', 'SHINE ON – Social Bar & Restaurant', 'Shine On Social Bar Huay Kaew Road Chiang Mai', 'Free', 'https://secure-content.meetupstatic.com/images/classic-events/524443312/676x380.jpg'),
  ('seed', 'hiit-fri', 'https://www.meetup.com/hiit-cnx/events/316523730/', 'HIIT Circuit Training & Social Chat', 'เวิร์กเอาต์ HIIT แล้วนั่งคุยกันต่อ', 'A high-intensity circuit workout for all levels, then a relaxed chat to cool down.
Circuit training with easier versions for beginners, followed by a chat to swap fitness tips.
Little English needed.
• Price not stated
• Bring workout clothes, water and a towel
• Little talking during the workout; just follow the moves', 'ออกกำลังกายแบบเซอร์กิตเข้มข้น ทุกระดับทำได้ แล้วคูลดาวน์ด้วยการนั่งคุยสบาย ๆ
เทรนแบบวงจร มีท่าดัดแปลงให้คนเพิ่งเริ่ม จากนั้นนั่งคุยแลกทิปส์ออกกำลังกายกัน
ใช้ภาษาอังกฤษน้อย
• ประกาศไม่ระบุค่าใช้จ่าย
• เตรียมชุดออกกำลังกาย น้ำ และผ้าขนหนู
• ช่วงออกกำลังแทบไม่ต้องพูด ดูท่าแล้วทำตามได้', '2026-10-02T11:00:00+07:00', '2026-10-02T13:00:00+07:00', 'Decathlon, Central Festival', 'Decathlon Central Festival Chiang Mai', 'Not stated', 'https://secure-content.meetupstatic.com/images/classic-events/534060221/676x380.jpg'),
  ('seed', 'conscious-tech', 'https://luma.com/xoukzfft', 'Conscious Technologists Unite!', 'Conscious Technologists ใช้เทคโนโลยีอย่างมีสติในยุค AI', 'A meetup for tech people interested in how digital tools are changing our thinking and attention.
News on consciousness and tech, experiences from practitioners, and ways to cope with tool overload.
Fluent English needed.
• Free; register on Luma
• The venue is shown on the registration page
• Some tech and psychology jargon', 'พบปะคนทำเทคที่สนใจว่าเครื่องมือดิจิทัลกำลังเปลี่ยนความคิดและสมาธิของเราอย่างไร
อัปเดตเรื่องจิตสำนึกกับเทคโนโลยี ฟังประสบการณ์จากผู้ปฏิบัติจริง และคุยวิธีรับมือกับเครื่องมือที่ล้นมือ
ต้องคุยภาษาอังกฤษได้คล่อง
• ฟรี ลงทะเบียนผ่าน Luma
• สถานที่แจ้งในหน้าลงทะเบียน
• มีศัพท์เฉพาะด้านเทคและจิตวิทยา', '2026-10-02T16:00:00+07:00', '2026-10-02T18:00:00+07:00', 'Shown on the registration page', 'Mueang Chiang Mai, Chiang Mai', 'Free', 'https://images.lumacdn.com/gallery-images/xj/227cc78a-750d-4529-9b8b-33481a4d61c8.png'),
  ('seed', 'temple-games', 'https://www.meetup.com/chiang-mai-meditation-buddhist-study-community/events/316525738/', 'Temple Game Night at Wat Tung Yu', 'คืนบอร์ดเกมที่วัดทุงยู', 'Strategy games, popcorn and new friends in a temple in the middle of town.
Games are provided, or bring your favourite to share. Bring food to share if you like.
Little English needed.
• Free; contributions for food and drinks welcome
• Games make it easy to connect even if your English isn''t fluent
• Dress modestly, it''s in a temple', 'เล่นเกมวางแผน กินป๊อปคอร์น และทำความรู้จักเพื่อนใหม่ในวัดกลางเมือง
มีเกมเตรียมไว้ให้ หรือเอาเกมที่ชอบมาเล่นกับคนอื่น เอาของกินมาแบ่งกันได้
ใช้ภาษาอังกฤษน้อย
• ฟรี ช่วยค่าอาหารและเครื่องดื่มได้ตามสะดวก
• เกมช่วยให้คุยกันง่าย แม้ภาษาอังกฤษไม่คล่อง
• แต่งกายสุภาพเพราะจัดในวัด', '2026-10-02T18:00:00+07:00', '2026-10-02T20:00:00+07:00', 'Wat Tung Yu', 'Wat Tung Yu Chiang Mai', 'Free', 'https://secure-content.meetupstatic.com/images/classic-events/531250868/676x380.jpg'),
  ('seed', 'friday-social', 'https://www.meetup.com/attika-studio-chiangmai/events/316238241/', 'Nomad Friday Social', 'Nomad Friday Social นั่งชิลคืนวันศุกร์', 'Comfy corners and good drinks; the organizer promises that if you come alone you''ll still find someone to talk to.
Hang out with regulars and new faces. Work clothes are fine; nobody cares how you''re dressed.
Conversational English is enough.
• Drop in any time between 7 and 11 pm
• It''s on the 3rd floor
• Entry price not stated', 'มุมนั่งนุ่ม ๆ เครื่องดื่มดี ๆ ผู้จัดบอกว่ามาคนเดียวก็มีคนคุยด้วยแน่นอน
นั่งคุยกับหน้าเก่าและเพื่อนใหม่ ใส่ชุดทำงานมาก็ได้ ไม่มีใครสนใจเรื่องการแต่งตัว
ภาษาอังกฤษพอคุยได้ก็พอ
• มาช่วงไหนก็ได้ระหว่างหนึ่งทุ่มถึงห้าทุ่ม
• ร้านอยู่ชั้น 3
• ประกาศไม่ระบุค่าเข้า', '2026-10-02T19:00:00+07:00', '2026-10-02T23:00:00+07:00', 'attika studio Café & Workshop (3rd floor)', 'attika studio 63 Tha Phae Road Chiang Mai', 'Not stated', 'https://secure-content.meetupstatic.com/images/classic-events/536204669/676x380.jpg'),
  ('seed', 'akha-songs-stories', 'https://culturalcrossroadsasia.org/event/tales-my-ancestors-taught-me/', 'Tales My Ancestors Taught Me: Akha songs and stories', 'Tales My Ancestors Taught Me ฟังเพลงและเรื่องเล่าของชาวอาข่า', 'An afternoon of traditional Akha songs, stories and martial arts, performed by master Akha musicians Athu Pochear, Miju Manpo and Mawleu Jupoh.
It opens the Melodies and Motifs in the Mountains exhibition at Chiang Mai City Craft Space.
Little English needed.
• Price not stated on the organizer''s page
• One hour, 4 to 5 pm
• On Tha Phae Road, an easy walk from the Old City', 'บ่ายหนึ่งของเพลง เรื่องเล่า และศิลปะการต่อสู้แบบดั้งเดิมของชาวอาข่า แสดงโดยครูนักดนตรีชาวอาข่า Athu Pochear, Miju Manpo และ Mawleu Jupoh
เป็นงานเปิดนิทรรศการ Melodies and Motifs in the Mountains ที่ Chiang Mai City Craft Space
ใช้ภาษาอังกฤษน้อย
• หน้าเว็บผู้จัดไม่ระบุค่าเข้า
• หนึ่งชั่วโมง 16:00–17:00 น.
• อยู่บนถนนท่าแพ เดินจากคูเมืองได้สบาย', '2026-10-03T16:00:00+07:00', '2026-10-03T17:00:00+07:00', 'Chiang Mai City Craft Space', '280 Tha Phae Road, Chang Moi, Chiang Mai 50300', 'Not stated', 'https://culturalcrossroadsasia.org/wp-content/uploads/2026/09/Tales-Ancestors-Concert-cover-1024x683.png')
on conflict (source, external_id) where external_id is not null do update set
  source_url = excluded.source_url,
  title_en = excluded.title_en,
  title_th = excluded.title_th,
  description_en = excluded.description_en,
  description_th = excluded.description_th,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  venue_name = excluded.venue_name,
  address = excluded.address,
  price_text = excluded.price_text,
  image_url = excluded.image_url;

-- event_tags
insert into event_tags (event_id, tag_id)
select e.id, v.tag_id from (values
  ('claude-impact-lab', 'tech'),
  ('ai-news-meetup', 'tech'),
  ('ai-business', 'tech'),
  ('conscious-tech', 'tech'),
  ('temple-cleanup', 'temples'),
  ('temple-games', 'temples'),
  ('akha-songs-stories', 'music'),
  ('akha-songs-stories', 'temples'),
  ('sunday-walking-street', 'street-food'),
  ('sunday-walking-street', 'design'),
  ('ecstatic-dance', 'music'),
  ('skate-create', 'design'),
  ('art-craft-circle', 'design'),
  ('sketch-club', 'design'),
  ('eco-printing-bua-bhat', 'design'),
  ('sunday-brunch', 'english'),
  ('new-in-town', 'english'),
  ('questions-family', 'english'),
  ('life-happened', 'english'),
  ('be-real', 'english')
) as v(external_id, tag_id)
join events e on e.source = 'seed' and e.external_id = v.external_id
on conflict do nothing;
