"""Regenerates tags/tags.sql and events/events.sql from the JSON seeds.

Run after editing tags.json, events.json or event-tags.json:  python3 scripts/seed/build_sql.py
The SQL files load straight into Postgres (psql -f), for when the admin upsert route isn't up.
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
EVENT_COLUMNS = ["source", "external_id", "source_url", "title_en", "title_th", "description_en", "description_th",
                 "starts_at", "ends_at", "venue_name", "address", "price_text", "image_url"]


def q(v):
    if v is None:
        return "null"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def build_tags():
    rows = json.loads((HERE / "tags/tags.json").read_text())["tags"]
    values = ",\n".join(f"  ({q(r['id'])}, {q(r['label_en'])}, {q(r['label_th'])}, {r['sort_order']})" for r in rows)
    sql = (f"-- Tags seed ({len(rows)}). Idempotent. Generated by build_sql.py from tags.json.\n"
           f"insert into tags (id, label_en, label_th, sort_order) values\n{values}\n"
           "on conflict (id) do update set label_en = excluded.label_en, label_th = excluded.label_th, "
           "sort_order = excluded.sort_order;\n")
    (HERE / "tags/tags.sql").write_text(sql)
    return {r["id"] for r in rows}


def build_events(tag_ids):
    events = json.loads((HERE / "events/events.json").read_text())["events"]
    links = json.loads((HERE / "events/event-tags.json").read_text())["event_tags"]
    ids = {e["external_id"] for e in events}
    assert set(links) <= ids, f"event-tags.json names unknown events: {set(links) - ids}"
    assert all(t in tag_ids for ts in links.values() for t in ts), "event-tags.json names an unknown tag"

    values = ",\n".join("  (" + ", ".join(q(e[c]) for c in EVENT_COLUMNS) + ")" for e in events)
    updates = ",\n  ".join(f"{c} = excluded.{c}" for c in EVENT_COLUMNS if c not in ("source", "external_id"))
    pairs = ",\n".join(f"  ({q(eid)}, {q(t)})" for eid, ts in links.items() for t in ts)
    sql = (f"-- Events seed ({len(events)}). Generated by build_sql.py from events.json and event-tags.json.\n"
           "-- Idempotent on (source, external_id); needs the contract's unique index on that pair.\n"
           f"insert into events ({', '.join(EVENT_COLUMNS)}) values\n{values}\n"
           f"on conflict (source, external_id) where external_id is not null do update set\n  {updates};\n\n"
           "-- event_tags\n"
           f"insert into event_tags (event_id, tag_id)\nselect e.id, v.tag_id from (values\n{pairs}\n) as v(external_id, tag_id)\n"
           "join events e on e.source = 'seed' and e.external_id = v.external_id\non conflict do nothing;\n")
    (HERE / "events/events.sql").write_text(sql)
    return len(events), sum(len(ts) for ts in links.values())


if __name__ == "__main__":
    tags = build_tags()
    n_events, n_links = build_events(tags)
    print(f"{len(tags)} tags, {n_events} events, {n_links} event-tag links")
