-- Tags seed (12). Idempotent. Generated by build_sql.py from tags.json.
insert into tags (id, label_en, label_th, sort_order) values
  ('english', 'English', 'ภาษาอังกฤษ', 10),
  ('thai-language', 'Thai language', 'ภาษาไทย', 20),
  ('cooking', 'Cooking', 'ทำอาหาร', 30),
  ('street-food', 'Street food', 'อาหารริมทาง', 40),
  ('scooter', 'Riding a scooter', 'ขี่มอเตอร์ไซค์', 50),
  ('bureaucracy', 'Visas & paperwork', 'วีซ่าและเอกสารราชการ', 60),
  ('temples', 'Temples & culture', 'วัดและวัฒนธรรม', 70),
  ('muay-thai', 'Muay Thai', 'มวยไทย', 80),
  ('hiking', 'Hiking', 'เดินป่า', 90),
  ('music', 'Music', 'ดนตรี', 100),
  ('tech', 'Tech & computers', 'เทคโนโลยีและคอมพิวเตอร์', 110),
  ('design', 'Design & crafts', 'งานออกแบบและงานฝีมือ', 120)
on conflict (id) do update set label_en = excluded.label_en, label_th = excluded.label_th, sort_order = excluded.sort_order;
